## 关于异常的总结

### 1.1处理异常的两种方式

#### 1.1.1 方式一：try catch抛出异常

如果方法内部抛出了异常，这个方法将会在抛出异常的过程中结束，如果不希望他结束，可以在方法内部放置一个代码块，来捕获异常。而 “try” 引导的方法块，相当于对可能出现异常的代码块进行一次尝试，他的逻辑是这样的：

```java
try{
    //可能会出现异常的代码块
}catch(type1 id1){
    //当出现这种异常时执行的代码
}catch(type2 id2){
    //当出现这种异常时执行的代码
}
...
```

当try中的代码块出现的异常类型于下面catch所定义的类型一致时，就会执行catch中的语句

这种执行逻辑好像有点类似于switch...case语句，但是与switch...case语句有一点是不同的：

当catch到某个类型的错误后，会直接执行其下面的语句块，执行完后会直接退出，不在往下面的catch执行，而case则会继续执行，所以需要在后面加break



#### 1.1.2 方式二： throw抛出异常

可以用throw来抛出异常，一种方式是在方法名后面加上一个throw和可能出现的异常列表

这种方式可以替代try catch方法

另一种就是配合if使用，如：

```java
if(){
    ....
}
throw new Exception;
```

